<a href="https://colab.research.google.com/github/Rizkysembiring0812/Google-Collab/blob/main/1st/MySkill.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import time
from sklearn.linear_model import LogisticRegression, LogisticRegressionCV
from sklearn.model_selection import GridSearchCV
from xgboost import XGBClassifier
from sklearn.metrics import confusion_matrix, classification_report, make_scorer,accuracy_score,precision_score,recall_score,f1_score
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

In [ ]:
path_1 = "https://raw.githubusercontent.com/brainspopper/dataset/main/FinanKu%20Data%20All.csv"
path_2 = "https://raw.githubusercontent.com/brainspopper/dataset/main/FinanKu%20Data%20Validasi.csv"
df_1 = pd.read_csv(path_1)
df_2 = pd.read_csv(path_2)

In [ ]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7561 entries, 0 to 7560
Data columns (total 22 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Customer ID               7561 non-null   int64  
 1   Branch Code               7561 non-null   int64  
 2   City                      7561 non-null   object 
 3   Age                       7561 non-null   int64  
 4   Avg. Annual Income/Month  7561 non-null   int64  
 5   Balance Q1                7561 non-null   float64
 6   NumOfProducts Q1          7561 non-null   int64  
 7   HasCrCard Q1              7561 non-null   int64  
 8   ActiveMember Q1           7561 non-null   int64  
 9   Balance Q2                7561 non-null   float64
 10  NumOfProducts Q2          7561 non-null   int64  
 11  HasCrCard Q2              7561 non-null   int64  
 12  ActiveMember Q2           7561 non-null   int64  
 13  Balance Q3                7561 non-null   float64
 14  NumOfPro

In [ ]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7561 entries, 0 to 7560
Data columns (total 22 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Customer ID               7561 non-null   int64  
 1   Branch Code               7561 non-null   int64  
 2   City                      7561 non-null   object 
 3   Age                       7561 non-null   int64  
 4   Avg. Annual Income/Month  7561 non-null   int64  
 5   Balance Q2                7561 non-null   float64
 6   NumOfProducts Q2          7561 non-null   int64  
 7   HasCrCard Q2              7561 non-null   int64  
 8   ActiveMember Q2           7561 non-null   int64  
 9   Balance Q3                7561 non-null   float64
 10  NumOfProducts Q3          7561 non-null   int64  
 11  HasCrCard Q3              7561 non-null   int64  
 12  ActiveMember Q3           7561 non-null   int64  
 13  Balance Q4                7561 non-null   float64
 14  NumOfPro

In [ ]:
df_1.duplicated().sum()

0

In [ ]:
df_2.duplicated().sum()

0

In [ ]:
df_1.isnull().sum()

Customer ID                 0
Branch Code                 0
City                        0
Age                         0
Avg. Annual Income/Month    0
Balance Q1                  0
NumOfProducts Q1            0
HasCrCard Q1                0
ActiveMember Q1             0
Balance Q2                  0
NumOfProducts Q2            0
HasCrCard Q2                0
ActiveMember Q2             0
Balance Q3                  0
NumOfProducts Q3            0
HasCrCard Q3                0
ActiveMember Q3             0
Balance Q4                  0
NumOfProducts Q4            0
HasCrCard Q4                0
ActiveMember Q4             0
Unpaid Tagging              0
dtype: int64

In [ ]:
df_2.isnull().sum()

Customer ID                 0
Branch Code                 0
City                        0
Age                         0
Avg. Annual Income/Month    0
Balance Q2                  0
NumOfProducts Q2            0
HasCrCard Q2                0
ActiveMember Q2             0
Balance Q3                  0
NumOfProducts Q3            0
HasCrCard Q3                0
ActiveMember Q3             0
Balance Q4                  0
NumOfProducts Q4            0
HasCrCard Q4                0
ActiveMember Q4             0
Balance Q5                  0
NumOfProducts Q5            0
HasCrCard Q5                0
ActiveMember Q5             0
Unpaid Tagging              0
dtype: int64

In [ ]:
df_1['Branch Code'].value_counts()

Branch Code
1024    977
1021    954
1023    929
1022    907
1011    403
1012    391
1013    387
1014    365
1015    352
1004    225
1005    220
1002    214
1003    214
1009    211
1001    211
1008    204
1007    201
1006    196
Name: count, dtype: int64

In [ ]:
df_2['Branch Code'].value_counts()

Branch Code
1024    977
1021    954
1023    929
1022    907
1011    403
1012    391
1013    387
1014    365
1015    352
1004    225
1005    220
1002    214
1003    214
1009    211
1001    211
1008    204
1007    201
1006    196
Name: count, dtype: int64

In [ ]:
df_1['City'].value_counts()

City
Surabaya    3767
Bandung     1898
Jakarta     1896
Name: count, dtype: int64

In [ ]:
df_2['City'].value_counts()

City
Surabaya    3767
Bandung     1898
Jakarta     1896
Name: count, dtype: int64

In [ ]:
df_1['Age'].value_counts()

Age
24    181
43    178
36    178
39    175
42    172
54    171
34    169
29    168
46    168
38    166
22    163
30    162
62    161
52    158
26    158
67    157
65    157
44    156
27    156
49    155
56    155
69    154
53    154
35    152
55    151
28    151
60    151
57    151
37    150
32    150
59    150
40    150
48    150
51    149
61    149
58    149
66    148
68    146
25    146
23    145
33    143
64    143
45    142
41    140
70    139
63    138
47    137
31    135
50    134
Name: count, dtype: int64

In [ ]:
df_2['Age'].value_counts()

Age
24    181
43    178
36    178
39    175
42    172
54    171
34    169
29    168
46    168
38    166
22    163
30    162
62    161
52    158
26    158
67    157
65    157
44    156
27    156
49    155
56    155
69    154
53    154
35    152
55    151
28    151
60    151
57    151
37    150
32    150
59    150
40    150
48    150
51    149
61    149
58    149
66    148
68    146
25    146
23    145
33    143
64    143
45    142
41    140
70    139
63    138
47    137
31    135
50    134
Name: count, dtype: int64

In [ ]:
df = pd.merge(df_1, df_2, on=['Customer ID', 'Branch Code', 'City', 'Age', 'Avg. Annual Income/Month', 'Balance Q2', 'NumOfProducts Q2', 'HasCrCard Q2', 'ActiveMember Q2', 'Balance Q3', 'NumOfProducts Q3', 'HasCrCard Q3', 'ActiveMember Q3', 'Balance Q4', 'NumOfProducts Q4', 'HasCrCard Q4', 'ActiveMember Q4', 'Unpaid Tagging'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5519 entries, 0 to 5518
Data columns (total 26 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Customer ID               5519 non-null   int64  
 1   Branch Code               5519 non-null   int64  
 2   City                      5519 non-null   object 
 3   Age                       5519 non-null   int64  
 4   Avg. Annual Income/Month  5519 non-null   int64  
 5   Balance Q1                5519 non-null   float64
 6   NumOfProducts Q1          5519 non-null   int64  
 7   HasCrCard Q1              5519 non-null   int64  
 8   ActiveMember Q1           5519 non-null   int64  
 9   Balance Q2                5519 non-null   float64
 10  NumOfProducts Q2          5519 non-null   int64  
 11  HasCrCard Q2              5519 non-null   int64  
 12  ActiveMember Q2           5519 non-null   int64  
 13  Balance Q3                5519 non-null   float64
 14  NumOfPro

In [ ]:
df['Mean Balance'] = (df['Balance Q1']+df['Balance Q2']+df['Balance Q3']+df['Balance Q4'])/4
df['Delta Balance'] = df['Balance Q5']-df['Balance Q1']

In [ ]:
df['Active Months'] = (df['ActiveMember Q1']+df['ActiveMember Q2']+df['ActiveMember Q3']+df['ActiveMember Q4']+df['ActiveMember Q5'])*3

In [ ]:
df['Diff PH'] = df['NumOfProducts Q5']-df['NumOfProducts Q1']

In [ ]:
def assign_cr1(df):
    if df['HasCrCard Q1'] == 1:
        return 15
    elif df['HasCrCard Q2'] == 1:
        return 12
    elif df['HasCrCard Q3'] == 1:
        return 9
    elif df['HasCrCard Q3'] == 1:
        return 6
    else:
        return 3
    return np.nan

In [ ]:
df['Vintage_CR'] = df.apply(assign_cr1, axis = 1)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5519 entries, 0 to 5518
Data columns (total 31 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Customer ID               5519 non-null   int64  
 1   Branch Code               5519 non-null   int64  
 2   City                      5519 non-null   object 
 3   Age                       5519 non-null   int64  
 4   Avg. Annual Income/Month  5519 non-null   int64  
 5   Balance Q1                5519 non-null   float64
 6   NumOfProducts Q1          5519 non-null   int64  
 7   HasCrCard Q1              5519 non-null   int64  
 8   ActiveMember Q1           5519 non-null   int64  
 9   Balance Q2                5519 non-null   float64
 10  NumOfProducts Q2          5519 non-null   int64  
 11  HasCrCard Q2              5519 non-null   int64  
 12  ActiveMember Q2           5519 non-null   int64  
 13  Balance Q3                5519 non-null   float64
 14  NumOfPro

In [ ]:
df = df.drop(columns = ['HasCrCard Q1', 'HasCrCard Q2', 'HasCrCard Q3', 'HasCrCard Q4', 'HasCrCard Q5'])

In [ ]:
df = df.drop(columns = ['Balance Q1', 'Balance Q2', 'Balance Q3', 'Balance Q4', 'Balance Q5'])

In [ ]:
df = df.drop(columns = ['NumOfProducts Q1', 'NumOfProducts Q2', 'NumOfProducts Q3', 'NumOfProducts Q4', 'NumOfProducts Q5'])

In [ ]:
df = df.drop(columns = ['ActiveMember Q1', 'ActiveMember Q2', 'ActiveMember Q3', 'ActiveMember Q4', 'ActiveMember Q5'])

In [ ]:
df

Customer ID  Branch Code      City  Age  Avg. Annual Income/Month  \
0        15565701         1001   Jakarta   29                  33000000   
1        15566091         1009   Jakarta   25                  12000000   
2        15566312         1009   Jakarta   43                  29000000   
3        15566495         1005   Jakarta   27                  15000000   
4        15566543         1003   Jakarta   68                  26000000   
...           ...          ...       ...  ...                       ...   
5514     15815295         1021  Surabaya   36                  38000000   
5515     15815530         1024  Surabaya   48                  29000000   
5516     15815615         1024  Surabaya   55                  18000000   
5517     15815628         1024  Surabaya   48                  18000000   
5518     15815645         1021  Surabaya   69                  20000000   

      Unpaid Tagging  Mean Balance  Delta Balance  Active Months  Diff PH  \
0                  1  2.967590e+05   1.305740e+06              9        0   
1                  0  3.379551e+05   1.622184e+06              6        0   
2                  0  2.775241e+05   4.311907e+05              6        1   
3                  0  5.306120e+07   1.365946e+07             12        0   
4                  0  1.099276e+08   5.402212e+07             12        2   
...              ...           ...            ...            ...      ...   
5514               1  1.241092e+08   6.118796e+06              6        0   
5515               0  1.374084e+05   5.203366e+05             12        1   
5516               0  1.685507e+08   0.000000e+00              0        0   
5517               0  0.000000e+00   0.000000e+00              0        0   
5518               0  3.784131e+07  -1.495900e+04             12        0   

      Vintage_CR  
0             15  
1             15  
2             15  
3             15  
4             15  
...          ...  
5514          15  
5515          15  
5516          15  
5517          15  
5518          15  

[5519 rows x 11 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5519 entries, 0 to 5518
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Customer ID               5519 non-null   int64  
 1   Branch Code               5519 non-null   int64  
 2   City                      5519 non-null   object 
 3   Age                       5519 non-null   int64  
 4   Avg. Annual Income/Month  5519 non-null   int64  
 5   Unpaid Tagging            5519 non-null   int64  
 6   Mean Balance              5519 non-null   float64
 7   Delta Balance             5519 non-null   float64
 8   Active Months             5519 non-null   int64  
 9   Diff PH                   5519 non-null   int64  
 10  Vintage_CR                5519 non-null   int64  
dtypes: float64(2), int64(8), object(1)
memory usage: 474.4+ KB


In [ ]:
df

Customer ID  Branch Code      City  Age  Avg. Annual Income/Month  \
0        15565701         1001   Jakarta   29                  33000000   
1        15566091         1009   Jakarta   25                  12000000   
2        15566312         1009   Jakarta   43                  29000000   
3        15566495         1005   Jakarta   27                  15000000   
4        15566543         1003   Jakarta   68                  26000000   
...           ...          ...       ...  ...                       ...   
5514     15815295         1021  Surabaya   36                  38000000   
5515     15815530         1024  Surabaya   48                  29000000   
5516     15815615         1024  Surabaya   55                  18000000   
5517     15815628         1024  Surabaya   48                  18000000   
5518     15815645         1021  Surabaya   69                  20000000   

      Unpaid Tagging  Mean Balance  Delta Balance  Active Months  Diff PH  \
0                  1  2.967590e+05   1.305740e+06              9        0   
1                  0  3.379551e+05   1.622184e+06              6        0   
2                  0  2.775241e+05   4.311907e+05              6        1   
3                  0  5.306120e+07   1.365946e+07             12        0   
4                  0  1.099276e+08   5.402212e+07             12        2   
...              ...           ...            ...            ...      ...   
5514               1  1.241092e+08   6.118796e+06              6        0   
5515               0  1.374084e+05   5.203366e+05             12        1   
5516               0  1.685507e+08   0.000000e+00              0        0   
5517               0  0.000000e+00   0.000000e+00              0        0   
5518               0  3.784131e+07  -1.495900e+04             12        0   

      Vintage_CR  
0             15  
1             15  
2             15  
3             15  
4             15  
...          ...  
5514          15  
5515          15  
5516          15  
5517          15  
5518          15  

[5519 rows x 11 columns]

In [ ]:
df['Branch Code'] = df['Branch Code'].astype(str)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5519 entries, 0 to 5518
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Customer ID               5519 non-null   int64  
 1   Branch Code               5519 non-null   object 
 2   City                      5519 non-null   object 
 3   Age                       5519 non-null   int64  
 4   Avg. Annual Income/Month  5519 non-null   int64  
 5   Unpaid Tagging            5519 non-null   int64  
 6   Mean Balance              5519 non-null   float64
 7   Delta Balance             5519 non-null   float64
 8   Active Months             5519 non-null   int64  
 9   Diff PH                   5519 non-null   int64  
 10  Vintage_CR                5519 non-null   int64  
dtypes: float64(2), int64(7), object(2)
memory usage: 474.4+ KB


In [ ]:
df = pd.get_dummies(df)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5519 entries, 0 to 5518
Data columns (total 30 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Customer ID               5519 non-null   int64  
 1   Age                       5519 non-null   int64  
 2   Avg. Annual Income/Month  5519 non-null   int64  
 3   Unpaid Tagging            5519 non-null   int64  
 4   Mean Balance              5519 non-null   float64
 5   Delta Balance             5519 non-null   float64
 6   Active Months             5519 non-null   int64  
 7   Diff PH                   5519 non-null   int64  
 8   Vintage_CR                5519 non-null   int64  
 9   Branch Code_1001          5519 non-null   bool   
 10  Branch Code_1002          5519 non-null   bool   
 11  Branch Code_1003          5519 non-null   bool   
 12  Branch Code_1004          5519 non-null   bool   
 13  Branch Code_1005          5519 non-null   bool   
 14  Branch C

In [ ]:
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

X = df.drop(['Unpaid Tagging'], axis=1)
y = df['Unpaid Tagging']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
smote = SMOTE(random_state=42)
X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)
print("X_train:")
print(X_train)
print("\ny_train:")
print(y_train)
print("\nX_test:")
print(X_test)
print("\ny_test:")
print(y_test)

X_train:
      Customer ID  Age  Avg. Annual Income/Month  Mean Balance  Delta Balance  \
4327     15702430   44                  56000000  1.036398e+06    1413906.500   
1844     15640865   30                  14000000  0.000000e+00          0.000   
5234     15786199   46                  17000000  0.000000e+00          0.000   
957      15734850   46                  23000000  0.000000e+00          0.000   
4055     15678720   58                  23000000  5.382215e+07    9829282.650   
...           ...  ...                       ...           ...            ...   
3772     15651352   23                   4000000  5.216266e+07    2391509.390   
5191     15781989   28                  39000000  5.883339e+04     235333.580   
5226     15785490   45                  15000000  5.292156e+04     116427.432   
5390     15802570   39                  19000000  9.507753e+07    9865110.680   
860      15718247   37                  23000000  7.696837e+07     463091.000   

      Active Month

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

knn = KNeighborsClassifier(n_neighbors=4)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=4)

In [ ]:
from sklearn import datasets
from sklearn import metrics
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sns
import xgboost as xgb

model = xgb.XGBClassifier()
model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [ ]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

svc_model = SVC(kernel='linear', C=1.0, random_state=42)

svc_model.fit(X_train, y_train)

SVC(kernel='linear', random_state=42)

In [ ]:
from sklearn import tree

dtree = tree.DecisionTreeClassifier()
dtree = dtree.fit(X_train, y_train)


In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=42, n_jobs=-1, max_depth=5,
                                       n_estimators=100, oob_score=True)

rf.fit(X_train, y_train)

RandomForestClassifier(max_depth=5, n_jobs=-1, oob_score=True, random_state=42)

In [ ]:
y_knn_pred = knn.predict(X_test)
y_svc = svc_model.predict(X_test)
y_pXG = model.predict(X_test)
y_dtree = dtree.predict(X_test)
y_rf = rf.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score
print("Akurasi KNN:",accuracy_score(y_test, y_knn_pred))
print("Akurasi SVC:",accuracy_score(y_test, y_svc))
print("Akurasi XGB:",accuracy_score(y_test, y_pXG))
print("Akurasi DT:",accuracy_score(y_test, y_dtree))
print("Akurasi RF:",accuracy_score(y_test, y_rf))

Akurasi KNN: 0.8206521739130435
Akurasi SVC: 0.8351449275362319
Akurasi XGB: 0.8161231884057971
Akurasi DT: 0.7327898550724637
Akurasi RF: 0.8351449275362319


In [ ]:
from sklearn.metrics import recall_score
print("Recall KNN:",recall_score(y_test, y_knn_pred, average='macro'))
print("Recall SVC:",recall_score(y_test, y_svc, average='macro'))
print("Recall XGB:",recall_score(y_test, y_pXG, average='macro'))
print("Recall DT:",recall_score(y_test, y_dtree, average='macro'))
print("Recall RF:",recall_score(y_test, y_rf, average='macro'))

Recall KNN: 0.6508783832035993
Recall SVC: 0.6604477611940298
Recall XGB: 0.660563807755481
Recall DT: 0.6613136470756267
Recall RF: 0.6604477611940298


In [ ]:
from sklearn.metrics import confusion_matrix
print("Confusion Matrix KNN:\n",confusion_matrix(y_test, y_knn_pred))
print("Confusion Matrix SVC:\n",confusion_matrix(y_test, y_svc))
print("Confusion Matrix XGB:\n",confusion_matrix(y_test, y_pXG))
print("Confusion Matrix DT:\n",confusion_matrix(y_test, y_dtree))
print("Confusion Matrix RF:\n",confusion_matrix(y_test, y_rf))

Confusion Matrix KNN:
 [[820  16]
 [182  86]]
Confusion Matrix SVC:
 [[836   0]
 [182  86]]
Confusion Matrix XGB:
 [[805  31]
 [172  96]]
Confusion Matrix DT:
 [[669 167]
 [128 140]]
Confusion Matrix RF:
 [[836   0]
 [182  86]]


In [ ]:
from sklearn.metrics import classification_report
print("KNeighbors:\n", classification_report(y_test, y_knn_pred))
print("Super Vector:\n", classification_report(y_test, y_svc))
print("XGBoost:\n", classification_report(y_test, y_pXG))
print("Decision Tree:\n", classification_report(y_test, y_dtree))
print("Random Forest:\n", classification_report(y_test, y_rf))

KNeighbors:
               precision    recall  f1-score   support

           0       0.82      0.98      0.89       836
           1       0.84      0.32      0.46       268

    accuracy                           0.82      1104
   macro avg       0.83      0.65      0.68      1104
weighted avg       0.82      0.82      0.79      1104

Super Vector:
               precision    recall  f1-score   support

           0       0.82      1.00      0.90       836
           1       1.00      0.32      0.49       268

    accuracy                           0.84      1104
   macro avg       0.91      0.66      0.69      1104
weighted avg       0.86      0.84      0.80      1104

XGBoost:
               precision    recall  f1-score   support

           0       0.82      0.96      0.89       836
           1       0.76      0.36      0.49       268

    accuracy                           0.82      1104
   macro avg       0.79      0.66      0.69      1104
weighted avg       0.81      0.82   

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, recall_score
from xgboost import XGBClassifier

model = XGBClassifier()

param_grid = {
    'max_depth': [3, 5, 10],
    'learning_rate': [0.01, 0.1, 0.3],
    'n_estimators': [100, 300, 500],
    'gamma': [0, 0.1, 0.2],
    'subsample': [0.5, 0.7, 1.0],
    'colsample_bytree': [0.5, 0.7, 1.0],
    'random_state': [42]
}

grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=5, scoring='accuracy')

grid_search.fit(X_train, y_train)

best_params = grid_search.best_params_
best_model = grid_search.best_estimator_

y_pred = best_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
recall = recall_score(y_test, y_pXG, average='macro')
print(f'Best Parameters: {best_params}')
print(f'Test Accuracy: {accuracy}')
print(f'Recall: {recall}')